name: publish docker image
on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Authenticate against ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image with version tag
        run: |
          docker build -t ghcr.io/dotmatthew/ghost-blog-s3:latest .
      - name: Build image with latest tag
        run: |
          docker tag ghcr.io/dotmatthew/ghost-blog-s3:latest \
          ghcr.io/dotmatthew/ghost-blog-s3:5.81
      - name: Push to github container registry
        run: |
          docker push --all-tags ghcr.io/dotmatthew/ghost-blog-s3
